name: Actualizar GTFS

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v2

      - name: Configurar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Instalar dependencias
        working-directory: ./scripts
        run: npm install

      - name: Ejecutar script de actualización
        working-directory: ./scripts
        run: node download_gtfs.js
      
      - name: Configurar Git y subir cambios
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add public/data/
          git commit -m "feat: Datos GTFS actualizados automáticamente"
          git push