jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v2

      - name: Configurar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Instalar dependencias
        # Agrega la línea 'working-directory' para apuntar a la carpeta 'scripts'
        # donde se supone que está tu package.json
        working-directory: ./scripts
        run: npm install

      - name: Ejecutar script de actualización
        # Si el script también está en 'scripts', mantén el working-directory
        working-directory: ./scripts
        run: node download_gtfs.js